CREATE TABLE IF NOT EXISTS repository (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT,
  maintainer TEXT NOT NULL,
  source_repository TEXT,
  arch TEXT NOT_NULL,
  kind TEXT NOT_NULL,
  tags TEXT,
  installed_size INTEGER NOT_NULL,
  license TEXT,
  v_major INTEGER NOT NULL,
  v_minor INTEGER NOT NULL,
  v_patch INTEGER NOT NULL,
  v_tag TEXT,
  v_readable TEXT NOT NULL,
  mandatory_dependencies TEXT,
  suggested_dependencies TEXT,
  index_timestamp BIGINT UNSIGNED NOT NULL
);